language: java
sudo: false
jdk:
- openjdk8
services:
  - postgresql
addons:
  postgresql: "10"
branches:
  only:
  - travis
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- cp seasonal-calendar-api/local.ci seasonal-calendar-api/local.properties
- psql -c 'create database "seasonal-calendars";' -U postgres
- chmod +x seasonal-calendar-api/gradlew
- chmod +x install.sh
- chmod +x deploy.sh
install:
- "./install.sh"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./deploy.sh'
env:
  global:
  - secure: D9WPmEVpXRdZY1N+B2EOQ8KbydL/f9HLv3cokJZRQcMP9cBnTRdbmYIOfymV8kPTefPr76ktEtj9HfBt4379fLNN3n2ynuwUG26JBl4OTRs82Xfwin7I+Usu05SDkRRoRrrRU7axlg0D7zyUcLaBh966pwCRUhkep7j1tDi8fPmllbY9CJe30ZI800VogVFJmKP6RaNblkdFNqopPDAcTtIOSUlAAw54svBb2nzZLNYcxszR4WHijklKln6yWUWBvNX/J/V5cqvcqV2A7drOA77kmkLHIPn//1/Els+OS3awFcYzFX7MwX//kMjTpdKeZ/+qdXZbqN+8y1zs/CtO5Wl2ggkhR9eEU+l3ZQMq6WEEwsBpkiecgrRdJ+vM4581nNeRFHZb7Oj+hOW/X/12Er3OlvUtsoOGIv4ft1030LqVgfdXuo0hKK2lkkHGt46/WFQfjkSFfpLrOG4is2jBs1OOwtD6RKWCwxXrctCv+Alt+lS4QALOJv0ib5eEWXAHdjeKTd2ha4BchHmxYHS0wrTmi/2mCsqXMeL4E0bAdLLxIwfmdvAAH0MqiV6Cdw/dhF9ooav9C2csKj/2cmY6MUAKN48+8zrEmEpfkKy3UEG+Cq+4y2u4jeXGHyY8VBeLS2nenumomRZ38+Q+c4PBwSGDqyQekcqhHU1aGSxir3c=
  - secure: cYjzrEkBKuhetO65autFI4xaBPuUa8Nr/hdoyVg0sAzDtkN/AXVck5vgvNExRvL8ITxc5DehpytQKcXFSL3s3AFUBn4mN82jv8XaEet5tGmy/EwgT+fnuF/JODN3BfrNIoaeodacmMA2glFnx2jT2v96ns8t8u6HTQ6pXdVFsoJ9BRmQhWxYgHFYj8UpnvXFjdqTaCa4RG8Kd2J8OEPp52WffkDTqSldVQlxRJ/0aLSLjiblllvrYSqLVqmd5Gt82MzgHeeJRV5+0UmAx0yL90R6nhioQ9/NpTPCYbPnHd+mBJYWlE14GDLouwiljBAG4IaCcRk3fbde/6wjFs7FqrmLi0sl1M9SAe04/pTNlKu25TYPRR6iTVdzcy7E79zblFXrE9Ey93M5STJkhZ2CAFIVm/yhUGK6ZgowJ5rg86EiWQfZjqE0wvPmEvXKlujkjSJjsKsOtobAFhQFlfXEgwmNkZaeSaZDuGWmZq6rUrFlG8xPFwBjYHXgmXZcwmR70v1b6mpJwODCK1Ly2ShGtTXAQrGGpC8d8nSUi5ibBEFvoadMskfXMMYTzEThhnoBTx9nMbSKYr54x4j5rcn1Omj5FN5Px0pNqiia3O/0qjwLlhPv8f2JasWXTLmV2m8niE2Kcv1rkafvg9oSez3wco6h3ZSyAHPMsFyPDd55Fn8=
