database:
#  driverClass: org.postgresql.Driver
#  url: jdbc:postgresql:seasonal-calendars
  dataSourceClass: org.postgresql.ds.PGSimpleDataSource
  properties:
#    serverName: localhost
#    portNumber: 5432
    user: postgres
    password: password
    databaseName: seasonal-calendars
flyway:
  outOfOrder: false
profileServiceBaseUrl: http://devt.ala.org.au:8099
dataResourceUid: dr382
httpClients:
  named:
    profile-service:
      readTimeout: PT30s
      headers:
        apiKey: 1234567890
logging:
  level: DEBUG
#server:
#  applicationConnectors:
#    - type: http
#      port: 8082