---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.calendar
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    config:
        locations:
            - file:///data/seasonal-calendar/config/seasonal-calendar-config.properties
            - file:///data/seasonal-calendar/config/seasonal-calendar-config.yml
            - file:///data/seasonal-calendar/config/seasonal-calendar-config.groovy
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents: false
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    assets:
        commonJs: false
endpoints:
    jmx:
        unique-names: true

bie.url: "https://bie.ala.org.au"

security:
    cas:
        uriFilterPattern: /calendar/index,/calendar/settings,/calendar/addCalendar,/calendar/editCalendar,/calendar/delete,/calendar/myCalendars
        uriExclusionFilterPattern: /assets/.*/images.*,/css.*,/js.*,.*json,/help/.*
        authenticateOnlyIfLoggedInFilterPattern: /,/;.*,/?.*,/[A-Za-z0-9]+/?,/calendar/myCalendars.*,/calendar/listMyCalendars.*,/calendar/settings.*,/calendar/addCalendar.*,/calendar/editCalendar.*,/calendar/delete.*
        alaAdminRole: ROLE_ADMIN,ROLE_SC_ADMIN

---
environments:
    development:
        grails:
            mongodb:
                host: localhost
                port: 27017
                databaseName: seasonal-calendar
    test:
        grails:
            mongodb:
                host: localhost
                port: 27017
                databaseName: seasonal-calendar-test
    production:
        grails:
            mongodb:
                host: localhost
                port: 27017
                databaseName: seasonal-calendar
